version: '3.1'

services:
  taskrr_pg:
    image: postgres:15.1
    container_name: taskrr_pg
    restart: always
    environment:
      POSTGRES_DB: taskrr_db
      POSTGRES_USER: utaskrr
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
